# Generated by Django 6.1.1 on 2026-09-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('region', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('global', 'Глобальный'), ('regional', 'Региональный'), ('local', 'Локальный')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Активный'), ('frozen', 'Замороженный'), ('resolved', 'Завершённый')], max_length=20)),
                ('cause', models.CharField(choices=[('territorial', 'Территориальный'), ('ethnic', 'Этнический'), ('economic', 'Экономический'), ('political', 'Политический'), ('religious', 'Религиозный')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('casualties_estimated', models.IntegerField(blank=True, null=True)),
                ('refugees_count', models.IntegerField(blank=True, null=True)),
                ('summary', models.TextField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('parties', models.JSONField(default=list)),
                ('sources', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
