"""
Django settings for conflict_map project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# При сборке в .exe (PyInstaller, frozen) код лежит в _MEIPASS,
# а БД и пользовательские файлы — рядом с .exe
if getattr(sys, 'frozen', False):
    # _MEIPASS — временная папка с кодом
    BUNDLE_DIR = Path(getattr(sys, '_MEIPASS', Path(__file__).resolve().parent.parent))
    # Папка рядом с exe — для БД (записываемая)
    APP_DIR = Path(sys.executable).resolve().parent
    BASE_DIR = BUNDLE_DIR
else:
    BASE_DIR = Path(__file__).resolve().parent.parent
    APP_DIR = BASE_DIR
    BUNDLE_DIR = BASE_DIR


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ny5($142i=()qd)=**uy=zbc%bgxdeemi4olote&i$w8&h&8%8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# --- Frontend (Vite build) ---
# В dev: ../frontend/dist, в exe: backend/frontend_dist внутри бандла
_CANDIDATES = [
    BASE_DIR / 'frontend_dist',
    BASE_DIR.parent / 'frontend' / 'dist',
    BUNDLE_DIR / 'frontend_dist',
]
FRONTEND_DIST = next((p for p in _CANDIDATES if (p / 'index.html').exists()), BASE_DIR / 'frontend_dist')

# Статика: frontend assets + django static
STATIC_URL = '/static/'
STATIC_ROOT = APP_DIR / 'staticfiles'
_frontend_assets = FRONTEND_DIST / 'assets'
_static_dir = BASE_DIR / 'static'
STATICFILES_DIRS = [d for d in [FRONTEND_DIST, _static_dir] if d.exists()]
# WhiteNoise — отдача статики без nginx, нужно для .exe
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'conflicts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 200,
}

ROOT_URLCONF = 'conflict_map.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [FRONTEND_DIST],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'conflict_map.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# В .exe БД хранится рядом с exe (чтобы была записываемая),
# при первом запуске копируется из бандла если её там нет.
def _resolve_db_path():
    bundled = BUNDLE_DIR / 'db.sqlite3'
    local = APP_DIR / 'db.sqlite3'
    if getattr(sys, 'frozen', False):
        if not local.exists() and bundled.exists() and bundled != local:
            try:
                import shutil
                shutil.copy2(bundled, local)
            except Exception:
                pass
        return local if (local.exists() or not bundled.exists()) else bundled
    return BASE_DIR / 'db.sqlite3'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': _resolve_db_path(),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/
# STATIC_URL определён выше (/static/) для WhiteNoise + .exe


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
